### ISSUE TITLE
Small screen rendering is terrible

### ISSUE THREAD

**Issue by AdamGarnsworthy** [GRIFFINCollaboration/beamCompanionExplorer#21]
Viewing the filtered plots on a small screen is terrible, all the tables overlap each other.

**Comment by katieannemills** [comment]
chrome only - I'll see what I can do, but if it's an emergency use ff until I close this.

**Comment by katieannemills** [comment]
> ~~chrome only~~ 

ooops nope, there it is in ff too...

Anyway, this is because dygraphs are not responsive after render; if you load the page _after_ changing your viewport size, it looks fine in ff and chrome. I'll see if I can force a redraw.

**Comment by katieannemills** [comment]
Fixed for me - let me know if that works for you.
