### ISSUE TITLE
Very slow response

### ISSUE THREAD

**Issue by AdamGarnsworthy** [GRIFFINCollaboration/beamCompanionExplorer#22]
Very slow response from server. Perhaps also worse with Chrome vs firefox but not confirmed.

**Comment by katieannemills** [comment]
what link are you seeing this from? All server requests return for me in <1s; we might be able to smarten this up a bit with proper minification; but if you're getting a huge lag, it's either your network (probably) or it's not the network at all, and your browser is doing too many things and struggling with the client side rendering (unlikely).

**Comment by AdamGarnsworthy** [comment]
http://griffincollaboration.github.io/beamCompanionExplorer/strippingFoil.html?species=Er&A=156&qOriginal=27
Google Chrome Version 46.0.2490.80 (64-bit)

**Comment by katieannemills** [comment]
alright - e17e486 produces about a 10% performance boost on load by deferring setting up plot saving until its needed, but I'm afraid that's as good as Dygraphs can do; drawing 28 interactive plots client side is always going to take a couple seconds: 

![screen shot 2015-11-19 at 2 52 39 pm](https://cloud.githubusercontent.com/assets/1896943/11282511/b7cd3b42-8ecd-11e5-86bc-aad150f33b65.png)

**Comment by AdamGarnsworthy** [comment]
On the second page, for example:
http://griffincollaboration.github.io/beamCompanionExplorer/strippingFoil.html?species=Er&A=156&qOriginal=25#chargeStateOption36
on initial load we could only generate the "Available charge states" list at the top and the plots for the original charge state. Then generate the plots for another charge state only when the user selects that charge state from the list at the top. I think that may make things simpler to use overall anyway - less scrolling.

**Comment by katieannemills** [comment]
This is a great idea - will do this weekend.

**Comment by AdamGarnsworthy** [comment]
Just be aware that a number of us are actively using this version you have on GitHub so will appreciate if it is available. Cheers!
