### ISSUE TITLE
Redundant graphs + suggestion

### ISSUE THREAD

**Issue by moukaddam** [GRIFFINCollaboration/beamCompanionExplorer#24]
(Issue changed, first point raised in my first complain was irrelevant)
It would be great to be able to collect these fraction in ascii format(A,Z,charge-state,fraction). Ultimately, one will use a spreadsheet to apply these fractions to the production yield of contaminants at the target, in order to decide what is the best A/Q to use.

**Comment by katieannemills** [comment]
I agree, a CSV output would be good, will do; exactly what calculation do you want to do here? I would recommend doing them with a python script (which I will also create if you want), rather than a spreadsheet; spreadsheets are a nuisance to input data into, and to debug.

**Comment by moukaddam** [comment]
Thansk for the fast reply, the beamCompanionexplorer will give you the percentage of what would be transmitted (TRANS) at "this" A/Q. It would be the final answer if one starts with the same number of products for each isotope at the yield station. 

This is not the real scenario as you know, the user should take into account the production measured (PROD) at the yield station before the CSB http://mis.triumf.ca/science/planning/yield/beam. The spreadsheet is only used at the end for a simple operation (PROD \* TRANS% = final yield). 

It would be great to get the final value, but not all the isotopes are measured at the yield station, and some of them are measured several times (with different proton beam intensity, target etc...) so the user should select the closest case.

**Comment by katieannemills** [comment]
Alright, CSVs can be downloaded from a button below the plot - let me know if this isn't what you wanted.
