### ISSUE TITLE
Plot on the same scale

### ISSUE THREAD

**Issue by moukaddam** [GRIFFINCollaboration/beamCompanionExplorer#25]
It would be faster if all the plots (at the first stage of charge breeding) have the same scale, like it use to be in the old tool.

**Comment by katieannemills** [comment]
I'm curious what kind of calculation you're trying to do; we could do this, but it is a major complication since it will mean all plots affect all other plots, rather than being independent. Could there be a simpler way to help you do what you're trying to do?

**Comment by moukaddam** [comment]
In this case don't bother, I think it doesn't worth it. To be honest it will not make things better, it's only "the cherry on the cake".

**Comment by katieannemills** [comment]
OK, I just implemented a draft of this (not live yet) - but there's a bit of an issue; consider for example [50K](http://griffincollaboration.github.io/beamCompanionExplorer/CSB.html?species=K&A=50). The x-axis ranges are so different, that if you set each minimum to the global minimum, and same for the maxima, each graph ends up squished into a tiny band with a lot of blank space: 

![screen shot 2015-11-25 at 8 33 01 pm](https://cloud.githubusercontent.com/assets/1896943/11415134/d0c0dd30-93b3-11e5-88d1-f01cbbc6d975.png)

![screen shot 2015-11-25 at 8 34 48 pm](https://cloud.githubusercontent.com/assets/1896943/11415152/148ff96a-93b4-11e5-912c-529e3a90a765.png)

![screen shot 2015-11-25 at 8 34 55 pm](https://cloud.githubusercontent.com/assets/1896943/11415154/1733bf8a-93b4-11e5-8c0b-ccff20fef3ef.png)

Happy to implement something like this, if you can suggest how to keep all the plots legible when their scales are very disjoint.

**Comment by moukaddam** [comment]
Good thing you did it, I meant the y axis! My bad..

**Comment by katieannemills** [comment]
et voila, let me know if this is what you wanted.

**Comment by moukaddam** [comment]
It's easier to compare the graphs at a glance now, this is exactly what is needed, thank you.
