### ISSUE TITLE
Color coding and "all contaminants" option

### ISSUE THREAD

**Issue by moukaddam** [GRIFFINCollaboration/beamCompanionExplorer#26]
(in the second filter stage) 

I think that the "all contaminant" option should be the default.  it is not easy to estimate that from the 2D plot, these contributions could be substantial sometimes and very easy to miss.

Also a color coding of the circles in the 2D plots will make it easy for the user to identify the origin of the contaminant. we have a list 4 ensembles (e.g. CSB Known Stable Contaminants), we can have a unified color of the isotops in the list and the circles in the 2D plot.

**Comment by katieannemills** [comment]
'all contaminants': sure.

'color coding': we actually tried this during development, it wasn't as good as you'd hope; the problem is that most of the contaminants (particularly the most interesting ones in the acceptance region) overlap so badly that the different colors weren't legible at all.

**Comment by moukaddam** [comment]
Ok, no problem.

**Comment by katieannemills** [comment]
although, one thing we could do for the color coding, is use traditional crosshair error bars instead of these big blobs; that way, individual things will be visible even if they are only slightly separated. We should discuss at the Thursday morning meeting.

**Comment by moukaddam** [comment]
the "All contaminant" option is not the default. I might have missed this discussion in the meeting..

**Comment by moukaddam** [comment]
Edit : I didnt see it was already done, my bad

**Comment by katieannemills** [comment]
Sorry for the confusion - if it says 'closed from a commit', that means this got done as requested without further debate.
