### ISSUE TITLE
Some basic new features

### ISSUE THREAD

**Issue by AdamGarnsworthy** [GRIFFINCollaboration/beamCompanionExplorer#5]
-I would like in the A/Q via A/Q plot to identify each data point on mouseover with its isotope label. The labeling of these plots always sucked in the old version.
-we need to also track the radioactive isobars which will accompany the beam. This was never done in the old version but should have been. The are especially important for the final 1D plot of A/Q vs charge state fraction.

**Comment by katieannemills** [comment]
Check out the demo at http://griffincollaboration.github.io/beamCompanionExplorer/strippingFoil.html#K/50/8
- isotope labels appear in the legend on mouseover
- a plot of charge fraction as a function of charge state for contaminants isobaric with the species of interest is generated.

Let me know any modifications / requests.

**Comment by AdamGarnsworthy** [comment]
Including radioactive isobars in the plots.

As an example we will consider 94Sr15+. This is accompanied by a number of stable isotopes including the stable isobar 94Mo. However it will also be accompanied by radioactive isobars which are currently not currently included in the plots and should be. 94Sr will beta decay to 94Y which will in turn decay to 94Zr etc until stability, so in the A=94 beam we will have 94Sr, 94Y, 94Zr, 94Nb, 94Mo.

In terms of coding this, you can identify which radioactive isobars will be the decay daughters by checking the masses. This method will work if you are on the neutron-deficient or neutron-rich side of the stability line. The less bound neighbouring isobar (94Rb) is further from stability and will not be a decay product. The more bound neighbouring isobar (94Y) will be more bound, and repeating this search you can build up the full group of decay daughters until you reach stability.

Now there is a second set of isobars which may be present in the beam in addition to the decay daughters of the species of interest. This is an isobar of an element which is easily surface-ionized and will be a contaminant in the beam. The example in the A=94 beam is Rb. So in addition to the above group, 94Rb and its decay daughters should also be added to the plots. In this case all decay daughters are already included so do not need to be double-counted. Another example is taking the example of a 63Co beam. Here the stable isobar (63Cu) is included, the decay daughter isobar of 63Co (63Ni), and the surface-ionized beam contaminant (63Ga) and its decay daughter (63Zn).

The lookup table, equivalent to my original $BadZ[1]=array();, for elements which should be considered as surface-ionized beam contaminants is as follows:
$SurfaceIonizedZ=array(3,11,19,21,22,29,31,37,38,39,49,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,81,87,88,89);
This table will not be 100% accurate for beams extracted from a FEBIAD ion source but that is operated much less frequently at ISAC, so I am happy with this for now.

**Comment by AdamGarnsworthy** [comment]
We also need to make sure that the stable nucleus that is the decay daughter is included in the plot. It might be in the "Other companions" group of table species, if so it needs to be moved into the included list for that case.

**Comment by katieannemills** [comment]
Cool, thanks - let's meet up 3ish on Monday to sort out any questions as I implement the last few features. I'd like to be feature complete by the end of Tuesday, so we can spend Wednesday doing quality assurance and testing, and ship on time.

**Comment by AdamGarnsworthy** [comment]
3pm Monday is good for me. I leave for Japan Tuesday morning.

-I like the list of buttons at the top of strippingfoil page. Can you also add the charge state fraction under the species.

**Comment by katieannemills** [comment]
> Can you also add the charge state fraction under the species.

implemented in https://github.com/GRIFFINCollaboration/beamCompanionExplorer/commit/14e34637fe1ba908b0a1dff6a98439b23bf55e3a

**Comment by katieannemills** [comment]
https://github.com/GRIFFINCollaboration/beamCompanionExplorer/commit/c2e427e32ce0b90c4d170a80019d27260720c4b1 introduces the surface ionization companions as requested; 63Co does indeed pick up a 63Ga background.

Also in the same commit, with all the things this issue wants to add to the plot, I had to split these objects (selected beam species, stable companions, surface ion companions) out into different color-coded series. A legend is forthcoming, but I don't think this will be enough to make these plots legible; we may need to consider falling back to more traditional points with error bars.

**Comment by AdamGarnsworthy** [comment]
Where is the latest demo now?

**Comment by BillMills** [comment]
file:///Users/billmills/Desktop/projects/beamCompanionExplorer/companionExplorer.html

**Comment by katieannemills** [comment]
http://griffincollaboration.github.io/beamCompanionExplorer/companionExplorer.html

**Comment by katieannemills** [comment]
Alright - this morning's commits nominally implement decay chain daughters. I also built a [test module describing the 63-Co behavior](http://griffincollaboration.github.io/beamCompanionExplorer/tests/tests.html?module=63-Co) @AdamGarnsworthy mentioned above. All the isotopes requested also appear in ie the [18+ selection of 63-Co](http://griffincollaboration.github.io/beamCompanionExplorer/strippingFoil.html?species=Co&A=63&qOriginal=9#chargeStateOption18) - so looks good on inspection of this test case. A few outstanding points before we close out:
- as promised, the plots are becoming very hard to read (esp. when saved as a png, without zooming and highlighting). Should move to crosshair error bars with shapes at their center to indicate different series.
- Might be worth rethinking the isotope lists on the right; I propose 4 independent lists:
  - CSB Companions: exactly the red letter companions from the original version
  - Other Stable Companions: black letter from original
  - Surface Ion Isobars
  - Decay chain daughters
- In implementing the surface ion and decay chain species, I assumed these were subject to the same conditions as the stable ions (ie, they have to make it through both selection magnets). Let me know if this was not what was intended.

**Comment by AdamGarnsworthy** [comment]
-Last bullet strategy is correct.
-Those lists sound good.
-maybe static labels like in the original would work for the saved file.

**Comment by AdamGarnsworthy** [comment]
Basic behavior looks correct, will test more from Japan.

**Comment by AdamGarnsworthy** [comment]
On the first page, analogous to the chatge state fraction in the buttons on the second page, in the buttons at the top add the average current in the acceptance region from each plot.

**Comment by katieannemills** [comment]
> On the first page, analogous to the chatge state fraction in the buttons on the second page, in the buttons at the top add the average current in the acceptance region from each plot.

implemented in https://github.com/GRIFFINCollaboration/beamCompanionExplorer/commit/9e3335e26ddb04d0a2a9c1936e0e00cf1f63db8b

**Comment by katieannemills** [comment]
everything in this thread is implemented in some form; closing out here, feel free to start new threads for any outstanding concerns.
