### ISSUE TITLE
pre-release candidate

### ISSUE THREAD

**Issue by katieannemills** [GRIFFINCollaboration/beamCompanionExplorer#6]
A 0.1 candidate is available [here](http://griffincollaboration.github.io/beamCompanionExplorer/companionExplorer.html); after @AdamGarnsworthy gives it the once-over, we can stamp a pre-release version and invite the rest of the community to give feedback.

**Comment by AdamGarnsworthy** [comment]
Good stuff.

-First page. It would be useful if there were a horizontal row of the charge state options which are displayed here (so the user knowns how many options there will be before scrolling all the way down). Ideally they will be links to jump down to that charge state section.
-FYI on a cell phone the divs all render as one per row on top of each other, so lots of scrolling. I'm not advocating major effort into supporting cell phone usage, just FYI.

second page;
-saving acceptance plot: no information on what is plotted. It needs a title or something saying what mass/element/charge state has been accelerated.
-On mouseover it would be nice if the small green dot to indicate which data point is highlighted were more obvious. Ideally it would be the same size as the datapoint and a different color.
-x axis title "A/Q (First stage, CSB-DSB)"
-y axis title "A/Q (After stripping, DSB-SEBT)"

-The charge state plot x axis should actually be the second A/q value, sorry for this. The legend should indicate what mass/element/charge state each point is, as well as the fraction.
-y axis title "% of total" should be "Charge State Fraction (%)"
-The charge state plot should include all species which are within the overlap region of the two orange acceptance windows on the a/q vs a/q plot (not just the stable isobar).

-We need to include the comments/ somewhere which indicate where the data comes from and what equations are used. Like a little "about" or help.

-My previous enhancement suggestion regarding isobars really is an additional functionality which was blatantly missing from the first version and really needs to be added. Its more work. I will explain it more clearly in a detailed response.

**Comment by katieannemills** [comment]
- https://github.com/GRIFFINCollaboration/beamCompanionExplorer/commit/b5a897c2fc21d2b1ef30ebf343330c33b4150d05 implements the scroll-to links for charge states on both pages. Notice that the old URLs will no longer work; had to re-think Ultralight to encode parameters in query string rather than URL hash, so we could use the URL hash's default behavior of scrolling to an id. So, instead of #K/50 after the url, try ?species=K&A=50 - I actually like this better, since it explicitly indicates the variable names.
- re: stacking on mobile: yep, that's on purpose and the magic of [Bootstrap](http://getbootstrap.com/). It's true, it does become a giant scroll, but that's because, according to the usability gurus, people expect a long vertical scroll on their phones, but not a horizontal one. One dimension to explore rather than two?

Other points will be addressed over the weekend.

**Comment by AdamGarnsworthy** [comment]
Looks good, I like it

**Comment by katieannemills** [comment]
progress (will update, or open new issues if further discussion required):
- ~~First page. It would be useful if there were a horizontal row of the charge state options which are displayed here (so the user knowns how many options there will be before scrolling all the way down). Ideally they will be links to jump down to that charge state section.~~
  done
- ~~saving acceptance plot: no information on what is plotted. It needs a title or something saying what mass/element/charge state has been accelerated.~~
  done
- ~~On mouseover it would be nice if the small green dot to indicate which data point is highlighted were more obvious. Ideally it would be the same size as the datapoint and a different color.~~
  done
- ~~x axis title "A/Q (First stage, CSB-DSB)"~~
  done
- ~~y axis title "A/Q (After stripping, DSB-SEBT)"~~
  done
- The charge state plot x axis should actually be the second A/q value, sorry for this. The legend should indicate what mass/element/charge state each point is, as well as the fraction.
- ~~y axis title "% of total" should be "Charge State Fraction (%)~~"
  done
- ~~The charge state plot should include all species which are within the overlap region of the two orange acceptance windows on the a/q vs a/q plot (not just the stable isobar).~~
  done
- ~~We need to include the comments/ somewhere which indicate where the data comes from and what equations are used. Like a little "about" or help.~~
  more discussion in #11

**Comment by katieannemills** [comment]
All of these requests are now implemented, except for the comment about the x axis of the charge state fraction graph being A/Q instead of charge state. These curves are paramerterized by Z only, and could correspond to more than one isotope for each element, leaving Z + charge state not enough information to map the charge state axis onto A/Q. We could do charge fraction per isotope rather than per element - is that what you want?

**Comment by katieannemills** [comment]
the only thing left from this list is #13 and #11 - closing out here.
