### ISSUE TITLE
A/Q uncertainty ellipses

### ISSUE THREAD

**Issue by katieannemills** [GRIFFINCollaboration/beamCompanionExplorer#7]
Currently, the A/Q uncertainties marked on the ellipses at `strippingFoil.html` are order-of-magnitude guesses at a match with the original version; would like a bit more rigor here. Recommendations welcome (cc @AdamGarnsworthy ).

**Comment by AdamGarnsworthy** [comment]
In the original code under file RFQ.php I made a plot of the energy spread in the RFQ which is the first section of separation, ie the x axis of the A/Q vs A/Q plot. There I use a value of 0.1% (factor 0.001) for the FWHM of the gaussian distribution. I remember I spend some time confirming this with the experts. So if we use a factor of 2*0.001 for the size of the blob then it will represent 2 sigma and therefore 95% of the ions. So my answer is (0.002 \* A/Q).
